/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsf.telas;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import nsf.dao.BeneficiarioDao;
import nsf.logica.Beneficiario;

/**
 *
 * @author augus
 */
public class telaCadastroBeneficiario extends javax.swing.JFrame {

    DefaultTableModel tmBeneficiario = new DefaultTableModel(null, new String[]{"ID", "Nome", "CPF", "RG", "Endereço", "Bairro", "Cidade", "Estado", "Fone", "OBS"});
    List<Beneficiario> beneficiarios;
    ListSelectionModel lsmBeneficiario;

    public telaCadastroBeneficiario() {
        initComponents();
        desabilitaDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlid = new javax.swing.JLabel();
        jlnome = new javax.swing.JLabel();
        jlcpf = new javax.swing.JLabel();
        jlrg = new javax.swing.JLabel();
        jlendereço = new javax.swing.JLabel();
        jlbairro = new javax.swing.JLabel();
        jlcontato = new javax.swing.JLabel();
        jlcidade = new javax.swing.JLabel();
        jlestado = new javax.swing.JLabel();
        jtid = new javax.swing.JTextField();
        jtnome = new javax.swing.JTextField();
        jtcpf = new javax.swing.JTextField();
        jtrg = new javax.swing.JTextField();
        jtendereco = new javax.swing.JTextField();
        jtbairro = new javax.swing.JTextField();
        jtcontato = new javax.swing.JTextField();
        jtcidade = new javax.swing.JTextField();
        jtestado = new javax.swing.JTextField();
        jlobs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtobs = new javax.swing.JTextArea();
        toolBarCadastro = new javax.swing.JToolBar();
        jbNovo = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTTabelaBeneficiario = new javax.swing.JTable();
        jtPesquisar = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14))); // NOI18N

        jlid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlid.setText("ID:");

        jlnome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlnome.setText("Nome:");

        jlcpf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlcpf.setText("CPF:");

        jlrg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlrg.setText("RG:");

        jlendereço.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlendereço.setText("Endereço:");

        jlbairro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbairro.setText("Bairro:");

        jlcontato.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlcontato.setText("Contato:");

        jlcidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlcidade.setText("Cidade");

        jlestado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlestado.setText("Estado: ");

        jtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtidActionPerformed(evt);
            }
        });

        jtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnomeActionPerformed(evt);
            }
        });

        jlobs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlobs.setText("OBS: ");

        jtobs.setColumns(20);
        jtobs.setRows(5);
        jScrollPane1.setViewportView(jtobs);

        toolBarCadastro.setBorder(new javax.swing.border.MatteBorder(null));
        toolBarCadastro.setRollover(true);

        jbNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsf/telas/icones/PNG-48/Add.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.setFocusable(false);
        jbNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });
        toolBarCadastro.add(jbNovo);

        jbAlterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsf/telas/icones/PNG-48/Modify.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setFocusable(false);
        jbAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        toolBarCadastro.add(jbAlterar);

        jbExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsf/telas/icones/PNG-48/Delete.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setFocusable(false);
        jbExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });
        toolBarCadastro.add(jbExcluir);

        jbSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsf/telas/icones/PNG-48/Save.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setFocusable(false);
        jbSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        toolBarCadastro.add(jbSalvar);

        jbSair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsf/telas/icones/PNG-48/Exit.png"))); // NOI18N
        jbSair.setText("Sair");
        jbSair.setFocusable(false);
        jbSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });
        toolBarCadastro.add(jbSair);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jlestado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(jlcontato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtcontato, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jlid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jlobs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlendereço)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jlnome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jlcpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlrg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtrg, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jlbairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtbairro)
                                .addGap(18, 18, 18)
                                .addComponent(jlcidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolBarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtcpf, jtrg});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnome)
                    .addComponent(jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcpf)
                    .addComponent(jtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlrg)
                    .addComponent(jtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlendereço)
                    .addComponent(jtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbairro)
                    .addComponent(jtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcidade)
                    .addComponent(jtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlestado)
                    .addComponent(jtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcontato)
                    .addComponent(jtcontato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlobs)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toolBarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtbairro, jtcidade, jtcontato, jtcpf, jtendereco, jtestado, jtid, jtnome, jtrg});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Beneficiários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        JTTabelaBeneficiario.setModel(tmBeneficiario);
        JTTabelaBeneficiario.setSelectionMode(ListSelectionM­odel.SINGLE_SELECTION);
        lsmBeneficiario = JTTabelaBeneficiario.getSelectionModel();
        lsmBeneficiario.addListSelectionListener(new ListSelectionListener() { public void valueChanged(ListSelectionEvent e) { if (! e.getValueIsAdjusting()){ jtTabelaBeneficiarioLinhaSelecioanda(JTTabelaBeneficiario); } }
        });
        jScrollPane2.setViewportView(JTTabelaBeneficiario);

        jtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesquisarActionPerformed(evt);
            }
        });

        jbPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsf/telas/icones/PNG-48/Search.png"))); // NOI18N
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPesquisar))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtidActionPerformed

    private void jtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnomeActionPerformed

    private void jtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesquisarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        //FUNÇÃO PARA LIMPAR CAMPOS
        habilitaDados();
        jtnome.setText(" ");
        jtcpf.setText(" ");
        jtrg.setText(" ");
        jtendereco.setText(" ");
        jtbairro.setText(" ");
        jtcidade.setText(" ");
        jtestado.setText(" ");
        jtcontato.setText(" ");
        jtobs.setText(" ");

    }//GEN-LAST:event_jbNovoActionPerformed

       public void desabilitaDados() {
        jtid.setEditable(false);
        jtnome.setEditable(false);
        jtcpf.setEditable(false);
        jtrg.setEditable(false);
        jtendereco.setEditable(false);
        jtbairro.setEditable(false);
        jtcidade.setEditable(false);
        jtestado.setEditable(false);
        jtcontato.setEditable(false);
        jtobs.setEditable(false);
    }
        
        public void habilitaDados() {
        jtnome.setEditable(true);
        jtcpf.setEditable(true);
        jtrg.setEditable(true);
        jtendereco.setEditable(true);
        jtbairro.setEditable(true);
        jtcidade.setEditable(true);
        jtestado.setEditable(true);
        jtcontato.setEditable(true);
        jtobs.setEditable(true);
    }
    public boolean verificaDados() {
        if (!jtnome.getText().equals("")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Campo NOME não Preenchido!");
            return false;
        }
    }
      //INSERINDO CAMPOS QUE SERÃO EXIBIDOS NA PESQUISA!
      private void jtTabelaBeneficiarioLinhaSelecioanda(JTable tabela) {
        if (JTTabelaBeneficiario.getSelectedRow() != -1) {
            habilitaDados();
            jtid.setText(String.valueOf(beneficiarios.get(tabela.getSelectedRow()).getBf_id()));
            jtnome.setText(beneficiarios.get(tabela.getSelectedRow()).getBf_nome());
            jtcpf.setText(beneficiarios.get(tabela.getSelectedRow()).getBf_cpf());
            jtrg.setText(beneficiarios.get(tabela.getSelectedRow()).getBf_rg());
            jtendereco.setText(beneficiarios.get(tabela.getSelectedRow()).getBf_endereco());
            jtbairro.setText(beneficiarios.get(tabela.getSelectedRow()).getBf_bairro());
            jtcidade.setText(beneficiarios.get(tabela.getSelectedRow()).getBf_cidade());
            jtestado.setText(beneficiarios.get(tabela.getSelectedRow()).getBf_estado());
            jtcontato.setText(beneficiarios.get(tabela.getSelectedRow()).getBf_fone());
            jtobs.setText(beneficiarios.get(tabela.getSelectedRow()).getBf_obs());
        } else {
            jtid.setText("");
            jtnome.setText("");
            jtcpf.setText("");
            jtrg.setText("");
            jtendereco.setText("");
            jtbairro.setText("");
            jtcidade.setText("");
            jtestado.setText("");
            jtcontato.setText("");
            jtobs.setText("");

        }

    }

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        if (verificaDados()) {
            cadastro();
            desabilitaDados();
            try {
                listarBeneficiario();
            } catch (SQLException ex) {
                Logger.getLogger(telaCadastroBeneficiario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        try {
            listarBeneficiario();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problema no campo de PESQUISA!");
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        try {
            excluirBeneficiario();
            listarBeneficiario();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problema na função EXCLUIR!");
        }
   
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        try {
            alterarBeneficiario();
            listarBeneficiario();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problema na função ALTERAR!");
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
setExtendedState( MAXIMIZED_BOTH );
    }//GEN-LAST:event_formWindowOpened

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
       telaCadastroBeneficiario.this.dispose(); 
        //new telaPrincipal().setVisible(true);
    }//GEN-LAST:event_jbSairActionPerformed
    
    public void alterarBeneficiario() throws SQLException{
        if(JTTabelaBeneficiario.getSelectedRow() != -1){
            if(verificaDados()){
                Beneficiario bf = new Beneficiario();
                BeneficiarioDao dao = new BeneficiarioDao();
                bf.setBf_id(Integer.valueOf(jtid.getText()));
                bf.setBf_nome(jtnome.getText());
                bf.setBf_cpf(jtcpf.getText());
                bf.setBf_rg(jtrg.getText());
                bf.setBf_endereco(jtendereco.getText());
                bf.setBf_bairro(jtbairro.getText());
                bf.setBf_cidade(jtcidade.getText());
                bf.setBf_estado(jtestado.getText());
                bf.setBf_fone(jtcontato.getText());
                bf.setBf_obs(jtobs.getText());
                dao.alterar(bf);
                JOptionPane.showMessageDialog(null, "Registro ALTERADO com SUCESSO !S");
            }
        }
    }
    
    public void excluirBeneficiario() throws SQLException {
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente EXCLUIR esse registro ? ",
                "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_NO_OPTION) {
            BeneficiarioDao dao = new BeneficiarioDao();
            dao.remove(beneficiarios.get(JTTabelaBeneficiario.getSelectedRow()));
        }
    }

//FUNÇÃO PARA PESQUISAR UM REGISTRO PELA INTERFACE
    public void listarBeneficiario() throws SQLException{
        BeneficiarioDao dao = new BeneficiarioDao();
        beneficiarios = dao.getLista("%" + jtPesquisar.getText() +"%");
        mostrarPesquisa(beneficiarios);
    }
    
    public void cadastro(){
       try {
        //FUNÇÃO PARA SALVAR NOVO REGISTRO
        Beneficiario bf = new Beneficiario();
        bf.setBf_nome(jtnome.getText());
        bf.setBf_cpf(jtcpf.getText());
        bf.setBf_rg(jtrg.getText());
        bf.setBf_endereco(jtendereco.getText());
        bf.setBf_bairro(jtbairro.getText());
        bf.setBf_cidade(jtcidade.getText());
        bf.setBf_estado(jtestado.getText());
        bf.setBf_fone(jtcontato.getText());
        bf.setBf_obs(jtobs.getText());
        BeneficiarioDao dao = new BeneficiarioDao();
        dao.adiciona(bf);
           System.out.println("Cadastrado com sucesso!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problema na função de CADASTRO!");
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastroBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastroBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastroBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastroBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastroBeneficiario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTTabelaBeneficiario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlbairro;
    private javax.swing.JLabel jlcidade;
    private javax.swing.JLabel jlcontato;
    private javax.swing.JLabel jlcpf;
    private javax.swing.JLabel jlendereço;
    private javax.swing.JLabel jlestado;
    private javax.swing.JLabel jlid;
    private javax.swing.JLabel jlnome;
    private javax.swing.JLabel jlobs;
    private javax.swing.JLabel jlrg;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JTextField jtbairro;
    private javax.swing.JTextField jtcidade;
    private javax.swing.JTextField jtcontato;
    private javax.swing.JTextField jtcpf;
    private javax.swing.JTextField jtendereco;
    private javax.swing.JTextField jtestado;
    private javax.swing.JTextField jtid;
    private javax.swing.JTextField jtnome;
    private javax.swing.JTextArea jtobs;
    private javax.swing.JTextField jtrg;
    private javax.swing.JToolBar toolBarCadastro;
    // End of variables declaration//GEN-END:variables

    private void mostrarPesquisa(List<Beneficiario> beneficiarios) {
        while(tmBeneficiario.getRowCount() > 0 ){
            tmBeneficiario.removeRow(0);
        }
       if(beneficiarios.size() == 0 ){
           JOptionPane.showMessageDialog(null, "Nenhum registro cadastrado!");
    }else{
           String[] linha = new String[] {null, null, null, null, null, null, null, null, null};
           for (int i = 0; i <  beneficiarios.size(); i++){
               tmBeneficiario.addRow(linha);
               tmBeneficiario.setValueAt(beneficiarios.get(i).getBf_id(),  i,  0);
               tmBeneficiario.setValueAt(beneficiarios.get(i).getBf_nome(),  i,  1);
               tmBeneficiario.setValueAt(beneficiarios.get(i).getBf_cpf(),  i,  2);
               tmBeneficiario.setValueAt(beneficiarios.get(i).getBf_rg(),  i,  3);
               tmBeneficiario.setValueAt(beneficiarios.get(i).getBf_endereco(),  i,  4);
               tmBeneficiario.setValueAt(beneficiarios.get(i).getBf_bairro(),  i,  5);
               tmBeneficiario.setValueAt(beneficiarios.get(i).getBf_cidade(),  i,  6);
               tmBeneficiario.setValueAt(beneficiarios.get(i).getBf_estado(),  i,  7);
               tmBeneficiario.setValueAt(beneficiarios.get(i).getBf_fone(),  i,  8);
               tmBeneficiario.setValueAt(beneficiarios.get(i).getBf_obs(),  i,  9);
               
           }
       }}
}
